### ISSUE TITLE
ImportError: cannot import name 'constants'

### ISSUE THREAD

**Issue by nand2** [flux3dp/beam-studio#2]
Hi!

Loading a brand new beam-studio 1.16 on Ubuntu 18.04 (nothing configured yet besides the IP of the Beamo), loading an image will get stuck at "Loading image, please wait ... [cancel]".
Looking at the console, I see every second the following output : 
```
[2020-02-09 11:33:59,ERROR,HTTP] Unhandle Error
Traceback (most recent call last):
  File "fluxghost/http_handler.py", line 38, in __init__
  File "socketserver.py", line 673, in __init__
  File "http/server.py", line 398, in handle
  File "http/server.py", line 386, in handle_one_request
  File "fluxghost/http_handler.py", line 61, in do_GET
  File "fluxghost/http_websocket_route.py", line 77, in get_match_ws_service
  File "importlib/__init__.py", line 109, in import_module
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "/home/jenkins/py-deploy-env/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fluxghost/websocket/toolpath.py", line 2, in <module>
  File "/home/jenkins/py-deploy-env/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fluxghost/api/bitmap_toolpath.py", line 6, in <module>
  File "/home/jenkins/py-deploy-env/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fluxclient/toolpath/laser.py", line 3, in <module>
  File "/home/jenkins/py-deploy-env/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fluxclient/toolpath/svgeditor_factory.py", line 20, in <module>
  File "/home/jenkins/py-deploy-env/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fluxsvg/__init__.py", line 29, in <module>
  File "/home/jenkins/py-deploy-env/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "fluxsvg/surface.py", line 25, in <module>
  File "/home/jenkins/py-deploy-env/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/cairocffi/__init__.py", line 16, in <module>
ImportError: cannot import name 'constants'
```
On the debug console I get : 
```
websocket.js?v=1581244332018:84 WebSocket connection to 'ws://127.0.0.1:44209/ws/discover' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
createWebSocket @ websocket.js?v=1581244332018:84
_ws.onclose @ websocket.js?v=1581244332018:196
websocket.js?v=1581244332018:84 WebSocket connection to 'ws://127.0.0.1:44209/ws/usb/interfaces' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
createWebSocket @ websocket.js?v=1581244332018:84
_ws.onclose @ websocket.js?v=1581244332018:196
usb-checker.js?v=1581244332018:124 usb checker onFatal
2websocket.js?v=1581244332018:84 WebSocket connection to 'ws://127.0.0.1:44209/ws/svgeditor-laser-parser' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
createWebSocket @ websocket.js?v=1581244332018:84
_ws.onclose @ websocket.js?v=1581244332018:196
websocket.js?v=1581244332018:84 WebSocket connection to 'ws://127.0.0.1:44209/ws/push-studio' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
createWebSocket @ websocket.js?v=1581244332018:84
_ws.onclose @ websocket.js?v=1581244332018:196
inter-process.js?v=1581244332018:57 FATAL
websocket.js?v=1581244332018:84 WebSocket connection to 'ws://127.0.0.1:44209/ws/discover' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
createWebSocket @ websocket.js?v=1581244332018:84
_ws.onclose @ websocket.js?v=1581244332018:196
2websocket.js?v=1581244332018:84 WebSocket connection to 'ws://127.0.0.1:44209/ws/svgeditor-laser-parser' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
createWebSocket @ websocket.js?v=1581244332018:84
_ws.onclose @ websocket.js?v=1581244332018:196
websocket.js?v=1581244332018:84 WebSocket connection to 'ws://127.0.0.1:44209/ws/camera-calibration' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
createWebSocket @ websocket.js?v=1581244332018:84
_ws.onclose @ websocket.js?v=1581244332018:196
websocket.js?v=1581244332018:84 WebSocket connection to 'ws://127.0.0.1:44209/ws/image-tracer' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
createWebSocket @ websocket.js?v=1581244332018:84
_ws.onclose @ websocket.js?v=1581244332018:196
websocket.js?v=1581244332018:84 WebSocket connection to 'ws://127.0.0.1:44209/ws/push-studio' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
createWebSocket @ websocket.js?v=1581244332018:84
_ws.onclose @ websocket.js?v=1581244332018:196
inter-process.js?v=1581244332018:57 FATAL
```

Please find below the output of the debug tool : 
```
======::os::======
OS: Linux
ARCH: x64
RELEASE: 4.15.0-1067-oem
USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) BeamStudio/1.1.6 Chrome/73.0.3683.121 Electron/5.0.6 Safari/537.36


======::devices::======
""

======::backend::======
Not available


======::ws::======
[
  {
    "url": "/ws/discover",
    "log": [
      "> {cmd:poke,ipaddr:192.168.1.2} string",
      "> {cmd:poke,ipaddr:192.168.1.2} string",
      "> {cmd:poke,ipaddr:192.168.1.3} string",
      "> {cmd:poke,ipaddr:192.168.1.3} string",
      "> {cmd:poke,ipaddr:192.168.1.4} string",
      "> {cmd:poke,ipaddr:192.168.1.4} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.5} string",
      "> {cmd:poke,ipaddr:192.168.1.5} string",
      "> {cmd:poke,ipaddr:192.168.1.6} string",
      "> {cmd:poke,ipaddr:192.168.1.6} string",
      "> {cmd:poke,ipaddr:192.168.1.7} string",
      "> {cmd:poke,ipaddr:192.168.1.7} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.8} string",
      "> {cmd:poke,ipaddr:192.168.1.8} string",
      "> {cmd:poke,ipaddr:192.168.1.9} string",
      "> {cmd:poke,ipaddr:192.168.1.9} string",
      "> {cmd:poke,ipaddr:192.168.1.10} string",
      "> {cmd:poke,ipaddr:192.168.1.10} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.11} string",
      "> {cmd:poke,ipaddr:192.168.1.11} string",
      "> {cmd:poke,ipaddr:192.168.1.12} string",
      "> {cmd:poke,ipaddr:192.168.1.12} string",
      "> {cmd:poke,ipaddr:192.168.1.13} string",
      "> {cmd:poke,ipaddr:192.168.1.13} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.14} string",
      "> {cmd:poke,ipaddr:192.168.1.14} string",
      "> {cmd:poke,ipaddr:192.168.1.15} string",
      "> {cmd:poke,ipaddr:192.168.1.15} string",
      "> {cmd:poke,ipaddr:192.168.1.16} string",
      "> {cmd:poke,ipaddr:192.168.1.16} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.17} string",
      "> {cmd:poke,ipaddr:192.168.1.17} string",
      "> {cmd:poke,ipaddr:192.168.1.18} string",
      "> {cmd:poke,ipaddr:192.168.1.18} string",
      "> {cmd:poke,ipaddr:192.168.1.19} string",
      "> {cmd:poke,ipaddr:192.168.1.19} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.20} string",
      "> {cmd:poke,ipaddr:192.168.1.20} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.21} string",
      "> {cmd:poke,ipaddr:192.168.1.21} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.22} string",
      "> {cmd:poke,ipaddr:192.168.1.22} string",
      "> {cmd:poke,ipaddr:192.168.1.23} string",
      "> {cmd:poke,ipaddr:192.168.1.23} string",
      "> {cmd:poke,ipaddr:192.168.1.24} string",
      "> {cmd:poke,ipaddr:192.168.1.24} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.25} string",
      "> {cmd:poke,ipaddr:192.168.1.25} string",
      "> {cmd:poke,ipaddr:192.168.1.26} string",
      "> {cmd:poke,ipaddr:192.168.1.26} string",
      "> {cmd:poke,ipaddr:192.168.1.27} string",
      "> {cmd:poke,ipaddr:192.168.1.27} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.28} string",
      "> {cmd:poke,ipaddr:192.168.1.28} string",
      "> {cmd:poke,ipaddr:192.168.1.29} string",
      "> {cmd:poke,ipaddr:192.168.1.29} string",
      "> {cmd:poke,ipaddr:192.168.1.30} string",
      "> {cmd:poke,ipaddr:192.168.1.30} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.31} string",
      "> {cmd:poke,ipaddr:192.168.1.31} string",
      "> {cmd:poke,ipaddr:192.168.1.32} string",
      "> {cmd:poke,ipaddr:192.168.1.32} string",
      "> {cmd:poke,ipaddr:192.168.1.33} string",
      "> {cmd:poke,ipaddr:192.168.1.33} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.34} string",
      "> {cmd:poke,ipaddr:192.168.1.34} string",
      "> {cmd:poke,ipaddr:192.168.1.35} string",
      "> {cmd:poke,ipaddr:192.168.1.35} string",
      "> {cmd:poke,ipaddr:192.168.1.36} string",
      "> {cmd:poke,ipaddr:192.168.1.36} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.37} string",
      "> {cmd:poke,ipaddr:192.168.1.37} string",
      "> {cmd:poke,ipaddr:192.168.1.38} string",
      "> {cmd:poke,ipaddr:192.168.1.38} string",
      "> {cmd:poke,ipaddr:192.168.1.39} string",
      "> {cmd:poke,ipaddr:192.168.1.39} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.40} string",
      "> {cmd:poke,ipaddr:192.168.1.40} string",
      "> {cmd:poke,ipaddr:192.168.1.41} string",
      "> {cmd:poke,ipaddr:192.168.1.41} string",
      "> {cmd:poke,ipaddr:192.168.1.42} string",
      "> {cmd:poke,ipaddr:192.168.1.42} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.43} string",
      "> {cmd:poke,ipaddr:192.168.1.43} string",
      "> {cmd:poke,ipaddr:192.168.1.44} string",
      "> {cmd:poke,ipaddr:192.168.1.44} string",
      "> {cmd:poke,ipaddr:192.168.1.45} string",
      "> {cmd:poke,ipaddr:192.168.1.45} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.46} string",
      "> {cmd:poke,ipaddr:192.168.1.46} string",
      "> {cmd:poke,ipaddr:192.168.1.47} string",
      "> {cmd:poke,ipaddr:192.168.1.47} string",
      "> {cmd:poke,ipaddr:192.168.1.48} string",
      "> {cmd:poke,ipaddr:192.168.1.48} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.49} string",
      "> {cmd:poke,ipaddr:192.168.1.49} string",
      "> {cmd:poke,ipaddr:192.168.1.50} string",
      "> {cmd:poke,ipaddr:192.168.1.50} string",
      "> {cmd:poke,ipaddr:192.168.1.51} string",
      "> {cmd:poke,ipaddr:192.168.1.51} string",
      "> {cmd:poke,ipaddr:192.168.1.1} string",
      "> {cmd:poke,ipaddr:192.168.1.108} string",
      "> {cmd:poke,ipaddr:192.168.0.108} string",
      "> {cmd:poke,ipaddr:192.168.1.52} string",
      "> {cmd:poke,ipaddr:192.168.1.52} string",
      "> {cmd:poke,ipaddr:192.168.1.53} string",
      "> {cmd:poke,ipaddr:192.168.1.53} string"
    ]
  },
  {
    "url": "/ws/usb/interfaces",
    "log": [
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}",
      "> list string",
      "< {status: ok, h2h: {}, cmd: list, uart: []}"
    ]
  },
  {
    "url": "/ws/camera-calibration",
    "log": []
  },
  {
    "url": "/ws/svgeditor-laser-parser",
    "log": [
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**"
    ]
  },
  {
    "url": "/ws/svgeditor-laser-parser",
    "log": [
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**"
    ]
  },
  {
    "url": "/ws/image-tracer",
    "log": []
  },
  {
    "url": "/ws/push-studio",
    "log": []
  },
  {
    "url": "/ws/svgeditor-laser-parser",
    "log": [
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**"
    ]
  },
  {
    "url": "/ws/svgeditor-laser-parser",
    "log": [
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**",
      "**abnormal disconnection**"
    ]
  }
]

======::storage::======
beambox-preference={"should_remind_calibrate_camera":false,"mouse_input_device":"MOUSE","model":"fbm1","show_guides":false,"guide_x0":0,"guide_y0":0,"engrave_dpi":"medium"}

customizedLaserConfigs=[{"name":"Wood - 3mm Cutting","speed":5,"power":55,"repeat":1,"isDefault":true,"key":"wood_3mm_cutting"},{"name":"Wood - 5mm Cutting","speed":4,"power":55,"repeat":2,"isDefault":true,"key":"wood_5mm_cutting"},{"name":"Wood - Monochromic Engraving","speed":180,"power":30,"repeat":1,"isDefault":true,"key":"wood_bw_engraving"},{"name":"Wood - Shading Engraving","speed":80,"power":15,"repeat":1,"isDefault":true,"key":"wood_shading_engraving"},{"name":"Acrylic - 3mm Cutting","speed":4,"power":55,"repeat":1,"isDefault":true,"key":"acrylic_3mm_cutting"},{"name":"Acrylic - 5mm Cutting","speed":5,"power":55,"repeat":2,"isDefault":true,"key":"acrylic_5mm_cutting"},{"name":"Acrylic - Monochromic Engraving","speed":180,"power":30,"repeat":1,"isDefault":true,"key":"acrylic_bw_engraving"},{"name":"Acrylic - Shading Engraving","speed":80,"power":15,"repeat":1,"isDefault":true,"key":"acrylic_shading_engraving"},{"name":"Leather - 3mm Cutting","speed":3,"power":60,"repeat":1,"isDefault":true,"key":"leather_3mm_cutting"},{"name":"Leather - 5mm Cutting","speed":3,"power":60,"repeat":2,"isDefault":true,"key":"leather_5mm_cutting"},{"name":"Leather - Monochromic Engraving","speed":150,"power":30,"repeat":1,"isDefault":true,"key":"leather_bw_engraving"},{"name":"Leather - Shading Engraving","speed":80,"power":15,"repeat":1,"isDefault":true,"key":"leather_shading_engraving"},{"name":"Fabric - 3mm Cutting","speed":20,"power":50,"repeat":1,"isDefault":true,"key":"fabric_3mm_cutting"},{"name":"Fabric - 5mm Cutting","speed":20,"power":50,"repeat":1,"isDefault":true,"key":"fabric_5mm_cutting"},{"name":"Fabric - Monochromic Engraving","speed":150,"power":20,"repeat":1,"isDefault":true,"key":"fabric_bw_engraving"},{"name":"Fabric - Shading Engraving","speed":80,"power":15,"repeat":1,"isDefault":true,"key":"fabric_shading_engraving"},{"name":"Rubber - Monochromic Engraving","speed":140,"power":50,"repeat":1,"isDefault":true,"key":"rubber_bw_engraving"},{"name":"Glass - Monochromic Engraving","speed":150,"power":35,"repeat":1,"isDefault":true,"key":"glass_bw_engraving"},{"name":"Metal - Monochromic Engraving","speed":80,"power":50,"repeat":1,"isDefault":true,"key":"metal_bw_engraving"}]

defaultLaserConfigsInUse={"parameters":true,"wood_3mm_cutting":true,"wood_5mm_cutting":true,"wood_bw_engraving":true,"wood_shading_engraving":true,"acrylic_3mm_cutting":true,"acrylic_5mm_cutting":true,"acrylic_bw_engraving":true,"acrylic_shading_engraving":true,"leather_3mm_cutting":true,"leather_5mm_cutting":true,"leather_bw_engraving":true,"leather_shading_engraving":true,"fabric_3mm_cutting":true,"fabric_5mm_cutting":true,"fabric_bw_engraving":true,"fabric_shading_engraving":true,"rubber_bw_engraving":true,"glass_bw_engraving":true,"metal_bw_engraving":true}

flux-rsa-key=[hidden]

laser-defaults={"material":{"value":"custom","label":"Custom","data":{"laser_speed":3,"power":255}},"objectHeight":0,"isShading":true}

poke-ip-addr=192.168.1.1, 192.168.1.108, 192.168.0.108

printer-is-ready=true

printers=[]

length=8



======::generic::======
undefined
```

Thanks!

**Comment by nand2** [comment]
The issue was fixed after sending the same bug report through their support system.

Thanks!
